site_name: MATH & SNT
site_url: https://sites.google.com/view/mrchretien/accueil
repo_url: https://github.com/matchre
edit_uri: tree/master/docs/
site_description: Base expérimentale de travail avec MkDocs
docs_dir: docs


nav:
    - Accueil: index.md
    - recettes: recettes.md
    - toto: toto.md
    - Prerequis: prerequis.md
    - test: test.md
    - python:
      - installation: python/installation.md
      - installation: python/installation.md
      - installation: python/installation.md
      - detail: python/detail/installation.md


                                    # JUSTIFICATIONS
theme:
    name: material
    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # français
    palette:                        # Palettes de couleurs jour/nuit
      - scheme: default
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
      - scheme: slate
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
        - toc.integrate
        - header.autohide


markdown_extensions:
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed               # Volets glissants.  === "Mon volet"
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
    social:
        - icon: fontawesome/brands/github # ou autre
          link: https://github.com/matchre
        